//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Project()
        {
            this.Tbl_File = new HashSet<Tbl_File>();
        }
    
        public int PID { get; set; }
        public Nullable<int> TID { get; set; }
        public int SID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        [Required(ErrorMessage = "your project name")]
        [Display(Name = "Project Name")]
        [StringLength(45, ErrorMessage = "Maximum 45 character minimum 3", MinimumLength = 3)]
        [DataType(DataType.Text)]
        public string Pname { get; set; }
        [Display(Name = "Project Details")]
        [StringLength(245, ErrorMessage = "Maximum 245 character minimum 3", MinimumLength = 3)]
        [DataType(DataType.Text)]
        public string Pdetils { get; set; }
    
        public virtual Tbl_Course Tbl_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_File> Tbl_File { get; set; }
        public virtual Tbl_Semester Tbl_Semester { get; set; }
        public virtual Tbl_Student Tbl_Student { get; set; }
        public virtual Tbl_Teacher Tbl_Teacher { get; set; }
    }
}
