//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Teacher()
        {
            this.Tbl_Project = new HashSet<Tbl_Project>();
            this.Tbl_AssignCourse = new HashSet<Tbl_AssignCourse>();
        }
    
        public int TID { get; set; }
        [Required] 
          [Display(Name = "Teacher Name")] 
         [StringLength(45, ErrorMessage = "Maximum 45 character minimum 3", MinimumLength = 3)] 
         [DataType(DataType.Text)]

        public string Tname { get; set; }
        [Required(ErrorMessage = "please provide your Employee ID")] 
         [Display(Name = "Employee ID")] 
         [StringLength(12, ErrorMessage = "only Employee ID", MinimumLength = 5)]

        public string TEid { get; set; }
        [Required(ErrorMessage = "select your Degnation")] 
          [Display(Name = "Degnation")]

        public string Tdignation { get; set; }
        [Required(ErrorMessage = "please provide your Initial Name")] 
         [Display(Name = "Initial Name")] 
         [StringLength(6, ErrorMessage = "Maximum 6 and minimum 2", MinimumLength = 2)]

        public string TInitial { get; set; }
        [Required(ErrorMessage = "please provide your E-mail address")] 
         [Display(Name = "E-mail")] 
         [DataType(DataType.EmailAddress)] 
         [StringLength(30, ErrorMessage = "only E-mail address", MinimumLength = 5)]

        public string TEmail { get; set; }
        [Required(ErrorMessage = "please provide your phone number")] 
          [Display(Name = "Phone")] 
         [DataType(DataType.PhoneNumber)] 
         [StringLength(20, ErrorMessage = "only Phone Number address", MinimumLength = 5)]

        public string Tphone { get; set; }
        [Required(ErrorMessage = "please provide your username")] 
         [Display(Name = "User Name")] 
         [StringLength(30, ErrorMessage = "User Name", MinimumLength = 4)]

        public string TuserName { get; set; }
        [Required(ErrorMessage = "please provide your password")] 
         [Display(Name = " Password")] 
         [DataType(DataType.Password)] 
         [StringLength(30, ErrorMessage = "Password minmum 6 and maximum 30", MinimumLength = 6)]

        public string Tpassword { get; set; }
        [Display(Name = " Is Teacher")] 
         [DefaultValue(false)]

        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Project> Tbl_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AssignCourse> Tbl_AssignCourse { get; set; }
    }
}
