//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LanguageTag
    {
        public int TagID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual Tbl_Language Tbl_Language { get; set; }
        public virtual Tbl_Project Tbl_Project { get; set; }
    }
}
