//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Semester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Semester()
        {
            this.Tbl_AssignCourse = new HashSet<Tbl_AssignCourse>();
        }
    
        public int SemesterID { get; set; }
        [Required]
        [Display(Name = "Course Name")]
        [StringLength(100, ErrorMessage = "Only Semester Name Total Character 100", MinimumLength = 5)]
        public string SemesterName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AssignCourse> Tbl_AssignCourse { get; set; }
    }
}
