//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserInfo
    {
        public int UserId { get; set; }
        public string uFirstName { get; set; }
        public string uLastName { get; set; }
        public string UserName { get; set; }
        public string uEmail { get; set; }
        public string uPassword { get; set; }
        public string uPhoto { get; set; }
        public Nullable<bool> uActive { get; set; }
    }
}
